[api]
url = "https://api-ksh6.onrender.com/simulador"
api_key = "66e4e200-8340-43c3-b5e9-db90322b679f"
entrada = 0
vencimento_primeira_parcela = "2024-10-30"
vencimento_segunda_parcela = "2025-04-30"
taxa_seguro = 0.03
custo_rastreador = 3500.00
capitalizacao_ano = 0.0975
numero_parcelas = 6
taxa_desagio = 0.0155
data_desconto = "2024-03-24"